import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        
        <body className={inter.className}>
        <nav className="w-full">
          <div className="py-6 mx-auto max-w-3xl flex flex-row justify-between font-mono font-bold">
          <Link href='/'>
            <div className="hover:text-emerald-500 transition-colors duration-500">
              <p>home</p>
            </div>
            </Link>
            <Link href='/sign-in'>
            <div className="hover:text-emerald-500 transition-colors duration-500">
              <p>sign in</p>
            </div>
            </Link>
            <Link href='/sign-up'>
              <div className="hover:text-emerald-500 transition-colors duration-500">
                <p>sign up</p>
              </div>
            </Link>
          </div>
        </nav>{children}</body>
      </html>
    </ClerkProvider>
  );
}
